In [ ]:
## Numpy
- numerical python
- It works as creating arrays and mathematical operations and statistical operations

In [6]:
# importing numpy
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [6]:
len(dir(np))

620

In [7]:
# creating an array
a1 = np.array([1,2,3,4,5])

In [8]:
a1

array([1, 2, 3, 4, 5])

In [9]:
a1.ndim

1

In [10]:
a1.size

5

In [11]:
a1.shape

(5,)

In [12]:
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [13]:
a2.ndim

2

In [14]:
a2.size

10

In [15]:
a2.shape

(2, 5)

In [17]:
a3 = np.arange(1,31)

In [18]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [19]:
a3.ndim

1

In [20]:
a3.shape

(30,)

In [21]:
a3.reshape(2,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [51]:
a4 = a3.reshape(3,10)

In [52]:
a4.shape

(3, 10)

In [48]:
a3.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [59]:
a4[1:2,5:6]

array([[16]])

In [61]:
a4[1:2,1:10:2]

array([[12, 14, 16, 18, 20]])

In [62]:
a5 = a3.reshape(6,5)

In [64]:
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [67]:
a5[4:6,2:4]

array([[23, 24],
       [28, 29]])

In [70]:
a5[3:6:2,2:5:2]

array([[18, 20],
       [28, 30]])

In [80]:
a5[::5,1:6:3]

array([[ 2,  5],
       [27, 30]])

In [82]:
np.random.random()

0.3534896982581023

In [84]:
np.random.rand(1,10)

array([[0.99608192, 0.84072799, 0.07629995, 0.91499085, 0.15878095,
        0.71961943, 0.53214893, 0.47154922, 0.83617516, 0.97531902]])

In [85]:
np.random.randn(1,10)

array([[-2.18955741, -0.09301902,  0.80807925, -0.30442808,  0.29982271,
        -0.75842102,  1.13489062,  1.27302499,  2.01535552, -1.09362631]])

In [92]:
np.random.randint(91,100,5)

array([97, 98, 97, 96, 99])

In [112]:
ex = np.random.randint(1,1000,100)

array([878, 387, 629, 455, 858, 664, 909, 381, 629, 928, 912,  73, 543,
       484, 495, 129, 925, 704, 545, 467,  18, 928, 779, 692, 630, 670,
       256, 711, 882, 300, 451, 487, 995, 806, 582, 506,  59, 730, 569,
        80, 136, 603, 297, 232, 175, 117, 297, 203, 992, 392, 268, 949,
       646, 184, 474, 198, 482, 884, 523, 472, 476,  24, 370, 526, 868,
       527, 635, 196, 139, 250, 972, 119, 590, 514, 172, 987, 298, 417,
        91, 854, 533, 209, 171, 778, 199, 418, 960, 241, 250, 348, 224,
        33, 576, 780, 847, 238,  39, 408, 162, 736])

In [116]:
ex[ex%2!=0]

array([643, 545, 887,   3, 571, 347, 765, 435, 907, 819,  97, 119, 649,
       897, 111,  51, 661, 899, 233, 599, 545, 613, 639, 859, 733,  69,
       493, 127, 183, 293, 623, 265, 863,   7, 393,  13, 391, 203, 325,
       189, 123, 553, 859, 375, 885, 489,  83, 415, 419, 751, 561, 173,
       665, 707, 307, 407, 243])

In [23]:
ex1 = np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
ex2 = np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.hstack((ex1,ex2))

NameError: name 'ex1' is not defined

In [27]:
np.hsplit(ex1,5)

NameError: name 'ex1' is not defined

In [30]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [31]:
np.linspace(1,1000,100)

array([   1.        ,   11.09090909,   21.18181818,   31.27272727,
         41.36363636,   51.45454545,   61.54545455,   71.63636364,
         81.72727273,   91.81818182,  101.90909091,  112.        ,
        122.09090909,  132.18181818,  142.27272727,  152.36363636,
        162.45454545,  172.54545455,  182.63636364,  192.72727273,
        202.81818182,  212.90909091,  223.        ,  233.09090909,
        243.18181818,  253.27272727,  263.36363636,  273.45454545,
        283.54545455,  293.63636364,  303.72727273,  313.81818182,
        323.90909091,  334.        ,  344.09090909,  354.18181818,
        364.27272727,  374.36363636,  384.45454545,  394.54545455,
        404.63636364,  414.72727273,  424.81818182,  434.90909091,
        445.        ,  455.09090909,  465.18181818,  475.27272727,
        485.36363636,  495.45454545,  505.54545455,  515.63636364,
        525.72727273,  535.81818182,  545.90909091,  556.        ,
        566.09090909,  576.18181818,  586.27272727,  596.36363

In [35]:
a6 = np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [36]:
np.diagonal(a6)

array([1., 1., 1., 1.])

In [39]:
a7 = np.arange(1,31)

In [40]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
a8 = a7.reshape(6,5)

In [43]:
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
a8.diagonal()

array([ 1,  7, 13, 19, 25])

In [45]:
a8.max()

30

In [47]:
a8.min()

1

In [51]:
a8.mean()

15.5

In [52]:
a8.std()

8.65544144839919

In [53]:
a8.sum()

465

In [54]:
a8.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351,
       378, 406, 435, 465], dtype=int32)

In [55]:
a8.dot(2)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [59]:
a8.argmax()

29

In [60]:
a8.argmin()

0

In [61]:
a8.transpose()

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [62]:
a8.prod()

1409286144

## Saving array and Loading Array

In [63]:
n = np.array([[[1,2],[6,7]]])

In [66]:
n.shape

(1, 2, 2)

In [ ]:
np.save("array n",n)

In [ ]:
x = np.load("array n.npy")
x

In [67]:
np.exp(np.arange(1,11))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [70]:
np.median(a8)

15.5

In [74]:
np.percentile(a8,5)

2.45

In [75]:
np.sin(a8)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175],
       [ 0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162]])

In [78]:
a9 = np.arange(1,101)

In [80]:
import time,webbrowser
browsers = 3
count = 0
while count<=browsers:
    time.sleep(10)
    if count==1:
        webbrowser.open("http://apssdc.in")
    elif count==2:
        webbrowser.open("http://nrtec.ac.in")
    elif count==3:
        webbrowser.open("http://youtube.com")
    count+=1